name = "snmpcollector"
license = "MIT"
licenselink = "https://github.com/toni-moreno/snmpcollector/blob/master/LICENSE"
description = "Full featured Generic SNMP data collector with Web Administration Interface"
homepage = "https://snmpcollector.org/"
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Toni Moreno"
  homepage = "https://github.com/toni-moreno/snmpcollector"
