name = "SnmpCollector"
license = "MIT"
licenselink = "https://github.com/toni-moreno/snmpcollector/blob/master/LICENSE"
description = "SnmpCollector Documentation Site"
homepage = "https://docsy.dev"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = 0.53

[author]
  name = "The Docsy Authors"
  homepage = "https://docsy.dev"
